trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy Using Template'
    inputs:
      azureResourceManagerConnection: 'sc-az-spbs-prod'
      subscriptionId: '$(subscription-id)'
      resourceGroupName: '$(resource-group)'
      location: 'West Europe'
      csmFile: '**/main.bicep'
      csmParametersFileLink: '$(parameters-file-url)'
