resources:
  repositories:
  #- repository: spbs-github
  #  type: github
  #  endpoint: $(sc-infrastructure-github)
  #  name: lambda-snail/Infrastructure
  - repository: spbs-devops
    #endpoint: MyAzureReposGitServiceConnection
    type: git
    name: Spbs/infrastrucutre-parameters

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  #- checkout: spbs-github
  - checkout: spbs-devops
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy Using Template'
    inputs:
      azureResourceManagerConnection: 'sc-az-spbs-prod'
      subscriptionId: '$(subscription-id)'
      resourceGroupName: '$(resource-group)'
      location: 'West Europe'
      csmFile: '**/main.bicep'
      csmParametersFileLink: '$(parameters-file-url)'
